version: 2
jobs:
  build:
    working_directory: ~/unemployment-reminders
    docker:
      - image: circleci/python:3.7.4
        environment:
          FLASK_ENV: test
          SECRET_KEY: ""
          TWILIO_AUTH_TOKEN: ""
    steps:
      - checkout
      - run:
          command: |
            cd ./services/api
            sudo pip3 install -r requirements.txt
            sudo pip3 install -r requirements-dev.txt
      - run:
          command: |
            cd ./services/api
            nose2 -v
