version: 2
jobs:
  checkout:
    working_directory: ~/unemployment-reminders
    steps:
      - checkout
  test:
    working_directory: ~/unemployment-reminders/services/api
    docker:
      - image: circleci/python:3.7.4
        environment:
          FLASK_ENV: test
          SECRET_KEY: ""
          TWILIO_AUTH_TOKEN: ""
    steps:
      - run:
          command: |
            sudo pip3 install requirements.txt
            sudo pip3 install requirements-dev.txt
      - run:
          command: |
            nose2 -v
      - store_test_results:
          path: test-results