service: unemployment-reminders-api
# app and org for use with dashboard.serverless.com
app: unemployment-reminders
org: dbowen

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.stage_vars.${self:provider.stage}.aws_profile}
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: ${cf:unemployment-reminders-${self:provider.stage}.SecretsArn}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:custom.dynamo_db_table}"

custom:
  defaultStage: dev
  dynamo_db_table: unemployment-reminders
  stage_vars:
    dev:
      aws_profile: personal_crucial_dev
      bot_base_url: ''
    stage:
      aws_profile: ''
      bot_base_url: ''
    prod:
      aws_profile: ''
      bot_base_url: ''
  # WSGI Plugin: https://github.com/logandk/serverless-wsgi
  wsgi:
    app: api/wsgi.app
    pythonBin: python3
    packRequirements: false
  dynamodb:
    # https://github.com/99xt/serverless-dynamodb-local/issues/57#issuecomment-507005352
    start:
      host: dynamodb
      port: 8000
      noStart: true
    seed:
      init:
        sources:
          - table: ${self:custom.dynamo_db_table}
            sources: [./data/dynamo.seed.init.json]
    stages:
      - dev
  # Python requirements Plugin: https://github.com/UnitedIncome/serverless-python-requirements
#  pythonRequirements:
#    dockerizePip: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dynamodb-local

package:
  individually: false
  include:
    - '!./**'
    - 'api/**'
    - 'lib/**'
    - 'functions/**'
  exclude:
    - '**'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
    timeout: 6
    memorySize: 1024
    environment:
      FLASK_ENV: ${self:provider.stage}
      SECRETS_MANAGER_SECRET_ARN: ${cf:unemployment-reminders-${self:provider.stage}.SecretsArn}
      BOT_BASE_URL: ${self:custom.stage_vars.${self:provider.stage}.bot_base_url}
      # Tell wsgi handler about our basepath. Required in conjunction with serverless-domain-manager plugin.
      API_GATEWAY_BASE_PATH: ${self:provider.stage}
  poller:
    handler: functions/poller.lambda_handler
    events:
      - schedule: rate(5 minutes)
    timeout: 600
    memorySize: 1024
    environment:
      FLASK_ENV: ${self:provider.stage}
      SECRETS_MANAGER_SECRET_ARN: ${cf:unemployment-reminders-${self:provider.stage}.SecretsArn}

resources:
  Resources:
    RemindersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          # E.164 phone number. https://www.twilio.com/docs/glossary/what-e164
          - AttributeName: phone_number
            AttributeType: S
          # UTC ISO 8601 date
          - AttributeName: next_alert_at
            AttributeType: S
          # 1,0 Flag the alert as in progress
          - AttributeName: in_progress
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: gsi_queue
            KeySchema:
              - AttributeName: in_progress
                KeyType: HASH
              - AttributeName: next_alert_at
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                # monday, tuesday, wednesday, thursday, friday
                - alert_day
                # America/Chicago
                - timezone
                # UTC ISO 8601 date.
                - alert_time
              ProjectionType: INCLUDE
        KeySchema:
          - AttributeName: phone_number
            KeyType: HASH
        TableName: ${self:custom.dynamo_db_table}
